### ISSUE TITLE
Shows not playing in order

### ISSUE THREAD

**Issue by Hunk4TH** [fnord12/script.pseudotv#28] opened 2020-11-08 22:58 UTC
Has anyone had any luck with getting shows to play in order? For example S01E01 then play S01E02 etc? 

Also a little off topic would it be possible to make a script to just show the channel bug within playing a show/movie within Kodi's library? If that make sense? I watch a lot of Adult Swim Shows and would love if I could have Kodi display the Adult Swim channel bug in the right hand bottom corner. That's probably my favorite feature of Pseudotv besides having bumpers :)

**Comment by fnord12** [comment] 2020-11-11 18:49
The play in order setting should work fine using the Sort Method (Episode) option.  In release 4.5.1 I fixed an issue with sorting if you have more than 9 seasons, but otherwise it's always been working.  Let me know more details if that doesn't work for you.

**Comment by fnord12** [comment] 2020-11-11 18:57
Regarding the channel bug script, it's really something that would require tweaking your skin.  Details would differ based on the skin, but you'd modify (most likely) the VideoFullScreen.xml file and try to find some boolean condition - https://kodi.wiki/view/List_of_boolean_conditions - in the visible tag and point to the appropriate bug image in the texture tag.  I'm just not sure if any currently available boolean condition would be useful (like I don't see a way to check if the current playing item has a specific tag or something).  Sorry!

**Comment by fnord12** [comment] 2020-11-11 18:57
Regarding the channel bug script, it's really something that would require tweaking your skin.  Details would differ based on the skin, but you'd modify (most likely) the VideoFullScreen.xml file and try to find some boolean condition - https://kodi.wiki/view/List_of_boolean_conditions - in the visible tag and point to the appropriate bug image in the texture tag.  I'm just not sure if any currently available boolean condition would be useful (like I don't see a way to check if the current playing item has a specific tag or something).  Sorry!

**Comment by Hunk4TH** [comment] 2020-11-12 20:57
Is the  Sort Method (Episode) option an option in Pseudotv? I'm guessing it's in Smart Playlist? If so I can definitely try that.

I never knew about the boolean condition thing. I'll definitely look into that. I use the Embuary skin found here https://forum.kodi.tv/showthread.php?tid=320137 I appreciate you taking the time to reply :)

**Comment by fnord12** [comment] 2020-11-13 02:15
If you're creating a channel based as a single tv show, the option should appear on the same screen where you select the show.  If you're using a Smart Playlist (for a single show?  unusual, but I've done it too for various reasons) then there's the Play Shows In Order Advanced Rule, which should also work.  If you're trying to have a channel with multiple shows but play them in order, I'm not sure if the Advanced Rule will work the way you want.

**Comment by Hunk4TH** [comment] 2020-11-13 05:27
Oh no I have multiple shows and have the "play in order" rule set but it's always a random episode number which is why I was confused haha. Sorry for the confusion I should've been more clear on that. That's what I always thought that rule did but I guess I was wrong.

**Comment by fnord12** [comment] 2020-11-13 13:48
In that case create a Custom Playlist and select Order By Episode.  It will collate the shows by episode (i.e., all the S01E01s will come first).  And then you shouldn't need any Advanced Rules (unless your overall Mode is Random in which case you could use a Force Realtime rule for just that channel).

I had some more thoughts about the channel bug skin customization but give me a couple days to test it.

**Comment by Hunk4TH** [comment] 2020-11-13 15:53
Thanks I'll give the playlist a shot. And awesome looking forward to it! Please take your time.

**Comment by gonzo90017** [comment] 2020-11-14 04:59
It actually is possible to have multiple shows in a single channel and have them play in order. One show after the other. Although it takes a bit of work.

Select the show with the most episodes and create a new channel
This is going to be the main channel so be sure you choose your desired channel #
Open Channel Configuration
**Channel Type: TV Show**
**Show:** Show with most Episode (in this example Dragonball)
![1](https://user-images.githubusercontent.com/24837361/99139816-e89e4f80-25f0-11eb-9859-9ffad53361c4.png)

Create a new channel (this channel will not be seen so be sure you select a channel # you don’t plan on seeing) using the show with the 2nd  most episodes and do the same as above but make sure you enable:
**SHOW IN ORDER**
(or else episodes will not show up in order)
![2](https://user-images.githubusercontent.com/24837361/99139830-0e2b5900-25f1-11eb-88d4-75c64df84df3.png)

You also need to add the ADVANCED CHANNEL RULE:
**DON’T PLAY THIS CHANNEL**
(since we don’t want this channel showing up in the TV Guide)
![3](https://user-images.githubusercontent.com/24837361/99139847-3f0b8e00-25f1-11eb-812b-e4d6f645b035.png)

Repeat the process if you are going to add more channels.
Now we need to go back to our  (main channel) > ADVANCED CHANNEL RULES> INTERLEAVE ANOTHER CHANNEL> 
**CHANNEL NUMBER:**  Enter the channel of the number you want to combine with this one
**MIN INT COUNT: 1** (this will interleave this show after every 1 episode cycle)
**MAX INT COUNT: 1** (this will also interleave the show after every 1 episode cycle)
**STARTING EPISODE: 1** (this is the 1st episode that will be shown for this show) 

1st Interleave:
![4](https://user-images.githubusercontent.com/24837361/99139872-695d4b80-25f1-11eb-8325-bc0f11befa3e.png)



2nd Interleave
![5](https://user-images.githubusercontent.com/24837361/99139881-7e39df00-25f1-11eb-8c07-906615206e0d.png)



3rd Interleave
![6](https://user-images.githubusercontent.com/24837361/99139895-b2150480-25f1-11eb-853b-8c0c857768d2.png)


Finally we should add a couple of more Channel Rules.
**Play TV SHOWS IN ORDER** (this is the only way to get the “Main” show to show up in order.
**Force Resume Mode** 
**Pause when not watching**
(This will prevent pause the show whenever you are not watching it so you don’t miss a second! )
![7](https://user-images.githubusercontent.com/24837361/99139913-db359500-25f1-11eb-91a3-ceeb286787ea.png)


TROUBLE SHOOTING
You might run into a show that refuses to show up in episode order.  In my case Justice League:
Go to the **MAIN CHANNEL**. Make sure the interleave rule is set to start on Episode 1.
If that doesn’t work. You need to create a playlist:
Example:
Kodi> Videos> New Smart Playlist> Type> TV Shows> Name the Playlist> Justice League
New Rule>Title> is> Browse> Justice League> Ok
Order By> Episodes

Now go into PseudoTv’s Settings and instead of creating “TV SHOW” channel. Create a Playlist channel
Open Channel Configuration> Select Desired Channel #> Custom Playlist> Select Playlist
Go to the Main Channel and interleave the channel as usual

Another issue that might appear is that the channel resets after exiting PseudoTV (in other words. It goes back to Season 1 Epsisode 1 of the first show.) by using the exit dialog. To prevent this. When exiting PseudoTV. Press the stop button instead to exit (X on your keyboard).

**Comment by Hunk4TH** [comment] 2020-11-14 22:35
@gonzo90017 Wow thanks so much for the very detailed reply! Does seem like a lot of work but I'm in the process of playing around with it. Wouldn't Smart play list with sort by episode have the same effect or? also with your method I'm wondering if I can still use bumpers. Thanks again!!!

**Comment by gonzo90017** [comment] 2020-11-15 03:53
I'm pretty sure I tried the smart playlist but this was years ago. But i'm positive this was the only way that it worked for me. You're welcome to try.

You can still use bumpers. Bumpers would count as your 1st interleaved channel. So you would set them up exactly as explained above.

**Comment by fnord12** [comment] 2020-11-17 21:32
[Channel Bug.txt](https://github.com/fnord12/script.pseudotv/files/5556330/Channel.Bug.txt)

Hey Hunk4TH, i've attached some instructions regarding the "Channel Bug outside of PSTV" request.  Let me know if anything is unclear.  I didn't test in the Embuary because it has a lot of dependencies and i didn't want to install it, so let me know things aren't appearing in the expected places.

**Comment by fnord12** [comment] 2020-11-17 21:33
In order to get a "channel bug" image to display in regular Kodi, the VideoFullScreen.xml file in your skin needs to be edited.  If you are using the default Estuary skin, you will actually need to make a copy of the entire skin and import it as a new skin.  If you are using any other skin, you can find it in your addons folder.  To find your addons folder, you can use this link to find your userdata folder:

https://kodi.wiki/view/Userdata#Location

The addons folder shares a parent folder with the userdata folder.  So after you find your userdata folder, go up a directory and look for the addons directory.  To find your skin, look for the skin.*Your skin name* folder.  Within that folder, you first want to find the xml files.  Depending on the skin, these may be in a subfolder called xml, 720, 1080 or something else.  Within that folder, you should be able to find VideoFullScreen.xml.

Before you go further, make a backup of at least the VideoFullScreen.xml file (and maybe just the whole skin to be safe).

The general edit you need to make looks like the following.  You can put it near the very end of the file, just before the last two tags:

<control type="image" id="1">
	<depth>DepthOSDPopout</depth>
	<description>channel bug</description>
	<left>1100</left>
	<top>160r</top>
	<width>160</width>
	<height>100</height>
	<texture>$INFO[VideoPlayer.TVShowTitle].png</texture>
	<aspectratio aligny="bottom">keep</aspectratio>
	<visible>VideoPlayer.Content(Episodes)</visible>
</control>

Note that the above fits between a "control" start and end tag.  At the end of your file, there are  probably "controls" and "window" end tags.  Your new tagset is going inside the "controls" tag.  So the end of your file should now look like this:

		<control type="image" id="1">
			<depth>DepthOSDPopout</depth>
			<description>channel bug</description>
			<left>1100</left>
			<top>160r</top>
			<width>160</width>
			<height>100</height>
			<texture>$INFO[VideoPlayer.TVShowTitle].png</texture>
			<aspectratio aligny="bottom">keep</aspectratio>
			<visible>VideoPlayer.Content(Episodes)</visible>
		</control>
	</controls>
</window>

You can adjust the positioning of the logo using the position tags (left, top, etc).

This alone won't cause anything to show up.  The place where we are calling an image is inside the "texture" subtag.  Note that in my example, it is calling the TV Show Title and appending a .png.  So if you are playing a show called Venture Bros., it will look for an image called Venture Bros..png (I'm using an example where the show has its own period in the title, meaning that there are two periods in the image file).

Now you can create a channel bug image that looks like whatever you want, and name it "Venture Bros..png".  For example, if you already have an Adult Swim logo from PseudoTV, you can copy and rename that image.  The image should also be placed in your skin folder, in a subfolder called media.  It will likely contain one or multiple .xbt files.  You can place your new .png files alongside them.

The limitation here is obviously that you will have to duplicate the logo for as many shows as you want to use the logo.  It's not ideal but the problem is that there aren't a lot of other choices to pick from.  The way we are calling the image - $INFO[VideoPlayer.TVShowTitle] - is called an InfoLabel.  Kodi's available InfoLabels can be found here:

https://kodi.wiki/view/InfoLabels#Video_player

The only ones we can use are the ones in the Video Player section (and not the ones for PVR).  Personally i'd prefer to use Tag instead of TVShowTitle but the Kodi developers don't allow Tag to be called here for some reason.  Another option is VideoPlayer.Genre, but the problem with Genre is that usually the scrapers assign multiple genres and it might be inconsistent.  So Venture Bros. might have a genre of Comedy/ Adventure and Harvey Birdman might have a genre of Comedy / Satire or something else.  But you may want to experiment with using a different InfoLabel instead of having to create a duplicate image for each show.

Note also that this will be visible for episodes only.  If you also want the channel bugs for movies, you'd duplicate the control tagset and change the visible subtag to VideoPlayer.Content(Movies).  And you'd have to choose a different InfoLabel for the texture tag.  VideoPlayer.Title would be exhausting for movies so you may have to try to make Genre work at that point.

If you make a change to a skin file, it isn't immediately visible in the skin.  The slow way to see a change is to quit Kodi and restart it.  But a faster way is to map Kodi's built-in Skin Reset function to a key in your keymap.  So for example, you could map it to your F5 key (if you have one, with:

<F5>XBMC.ReloadSkin()</F5>

Replace the F5 tags with another key as desired.

Your keymap is in your userdata folder, in the keymaps subfolder.  If you don't have a keymap.xml file in your keymaps subfolder, you will have to create it.  In that case, the whole file should look like this:

<keymap>
    <global>
        <keyboard>
            <F5>XBMC.ReloadSkin()</F5>
		</keyboard>
	</global>
</keymap>

Mapping this will make it easier to test your logos, especially if you are trying to find a good position.

**Comment by Hunk4TH** [comment] 2020-11-18 19:55
> 
> 
> [Channel Bug.txt](https://github.com/fnord12/script.pseudotv/files/5556330/Channel.Bug.txt)
> 
> Hey Hunk4TH, i've attached some instructions regarding the "Channel Bug outside of PSTV" request. Let me know if anything is unclear. I didn't test in the Embuary because it has a lot of dependencies and i didn't want to install it, so let me know things aren't appearing in the expected places.

Wow thanks so much for the detailed instructions!  It did the trick. Now just trying to working on the position :D I really appreciate it! This should be a feature in Kodi imo. Its a weird request I know.

**Comment by fnord12** [comment] 2020-11-18 21:23
Glad it works for you!  I'm closing this but feel free to open a new issue if you run into problems.  In the future, please keep issues/requests in their own threads so that i can close/refer to them separately.

**Closed as completed by fnord12** 2020-11-18 21:23 UTC
