### ISSUE TITLE
Suggestion: Simple interleaving fork? Plus, true random ads

### ISSUE THREAD

**Issue by MattTheDoctor** [fnord12/script.pseudotv#23] opened 2020-08-11 18:43 UTC
Hi!

So, this new fork of Pseudo TV is great - I love the work you've done! However, I have some minor annoyances preventing it from suiting my needs and wanted to see if it was possible for a simplified side version. The workarounds for the duration of videos not being read (using ffmpeg for mp4 files to remux them to MKV, setting a default duration in the menu) have worked fine on my test instances but I'm really nervous for my projects that contain over 1000 files.

Ideally I'd like an add-on where you can take a main directory, select one or more other directories to interleave, set the min and max, and just...go. No EPG, no worrying about filetypes other than if Kodi can play them. Simple as that, maybe have the "reset every x days" option as well. Right now on my test instances there are always errors regarding duration even after the fixes, and while that hasn't actively prevented files from playing yet, it's a little concerning at times especially when looking to upsize this to programming lineups in the quadruple digits.

Second, I've set it up so that my interleaved ads channel plays an ad between every show. It works well, but in my tests I've noticed two things:
1. When it gets to the end of the randomized ad playlist it will start again at the start of the ad loop (so it'll play ads 1-6 and then start back at 1). It'd be nice if it would shuffle around ad order after reaching the end and starting again.

2. When it reaches the final show and loops back around, it doesn't play an ad before going back to the first show, and the ad playlist loops again. So in my example it went show 4 -> ad 1 -> show 5 -> ad 2 -> show 6 -> show 1 -> ad 1 -> Show 2 -> Ad 2, etc.

Honestly I've been pulling my hair out looking for a simple interleaving solution that I can have running 24/7 and while this fork is way better than all previous ones (and I super appreciate it) I think a true simple single-channel no duration version would be great for personal projects, businesses, and more. Heck, I'd even be happy to donate to get it done, it's been a heck of a time trying to find a solution.

Either way, keep up the great work. It's been really nice finally getting this to mostly work in my tests. Thanks a bunch.

**Comment by fnord12** [comment] 2020-08-12 01:51
Thanks for the feedback and suggestions!  What you're asking for isn't something i'm likely to do; this streamed down version would actually be a lot of work and the end result doesn't sound like PseudoTV anymore!  But i'll keep this all in mind when i'm in the code for other reasons, and maybe something will suggest itself.

**Comment by MattTheDoctor** [comment] 2020-08-12 09:48
That's totally fair - I am no coder (at least, not for Kodi) so I wasn't sure how much effort that would be. Perhaps instead would there be a way to output a log if a video in a directory is definitely skipped during channel generation/app startup? I guess I'm just paranoid because the old forks of PseudoTV would straight up just not play things sometimes and I'd rather not have to look through an EPG for 1000-3000 files to find the odd one out.

Also, what about the ad reshuffling after playing them all suggestion? Or is that something already possible that I missed?

Again, thanks for your help and the fast replies. It's very refreshing and nice to finally get some answers after poking around the Kodi forums and various subreddits and such.

**Comment by fnord12** [comment] 2020-08-12 15:10
When i addressed the duration problem, i made it so PSTV will always write to the main Kodi log when it can't determine the duration of a file (even if you don't have Debug mode activated and regardless of whether you've enabled the pop-up notification) .  So you could open up the log in something like Notepad++ and search for "Failed to find duration" (in Notepad++, you can "Find All in Opened Document" and get a nice panel of search results).   In most cases it will also provide the path of the problem file, and if it provides that it should mean that it was able to assign the default duration (if that's enabled).  If it's totally confused, it will display nothing instead of the path (Failed to find duration for directory video "") and those would be the cases where it's skipping the video.  In that case i would turn Debug mode on and run it again and the debug info prior to that line should give you a hint about which video it's probably skipping.  Since it's seems like you're doing this for a static and relatively small number of files, it seems like a test you could run once to confirm nothing's being skipped.

In terms of the reshuffling, i assume you have the Advanced Rule "Force Random Mode" for the interleave channel.  The problem is that when it takes from the interleave channel to create the merged final playlist, it's only a length equal to the number of videos, so it's just going to take from the same (randomized) interleave playlist over and over again.

Normally PSTV would reshuffle the playlist the next time you started PSTV (based on the Time Between Channel Resets setting) so it wouldn't be a big deal.  But it sounds like you're just letting it run 24/7, and so it's just reusing the originally generated playlist.  Normally the solution would be "get more content!".   One idea is to duplicate the files in your commercial channel until they match the number of actual videos, but then you couldn't guarantee that the same commercials wouldn't play in a row (or nearly in a row).

Another thing you can try is to manually edit the generated m3u playlist yourself.  You can find the generated playlists in \userdata\addon_data\script.pseudotv\cache, and you can open an m3u file in a text editor like Notepad++.  Note that each entry is two lines:

#EXTINF:122,Transformers ad 3//// We'll be right back after these messages! 
F:\Directories\Commercials\Transformers ad 3.mp4

I would set Time Between Channel Resets to Never, and then manually edit the merged channel playlist to randomize the commercials.  Make a copy of it because the file is stored in a cache area that might get erased even with Resets being set to Never.  But that might work.  I wouldn't recommend this to most people but since you seem to just have a static number of videos, it might be a solution for you after the initial up-front work.

**Comment by MattTheDoctor** [comment] 2020-08-12 21:17
Hi again!

Thanks so much for this peek under the hood and all this fantastic advice. I've used it to dig deep and get my channels up-and-running. Dream come true type stuff and it works like a charm so far. Looking into the logs it looks like all 3,456 videos are queued up with nothing missing, and that's a HUGE weight off my shoulders. Seriously, I'm so glad you took this project under your wing and can't thank you enough for the quick responses, informative discussion, and patience.

**Comment by fnord12** [comment] 2020-08-12 22:50
Glad this was helpful!

**Closed as completed by fnord12** 2020-08-12 22:50 UTC
Labels: support
